import type { Affair } from "@/lib/types";

type dummyProp = {
  [key: string]: Affair[];
};

export default function useDummy() {
  const dummy: dummyProp = {
    "3/1/2024": [
      {
        id: "aasdfqytrjrytjhherteeadsfqsd",
        userId: "harrypotter",
        title: "event 3",
        color: "#FFC85D",
        type: "event",
        time1: new Date(2024, 2, 1, 22, 0),
        time2: new Date(2024, 2, 4, 22, 0),
        dateString: "3/1/2024",
        isDone: false,
        order: 0,
      },
      {
        id: "sandllllllra",
        userId: "harrypotter",
        title: "concert",
        color: "#F3935D",
        type: "todo",
        time1: new Date(2024, 2, 1, 22, 0),
        time2: new Date(2024, 1, 1, 4, 0),
        dateString: "3/1/2024",
        isDone: true,
        order: 1,
      },
      {
        id: "opjppppppppm",
        userId: "harrypotter",
        title: "看書",
        color: "#F1922A",
        type: "todo",
        time1: new Date(2024, 2, 1, 22, 0),
        time2: new Date(2024, 1, 1, 9, 30),
        dateString: "3/1/2024",
        isDone: true,
        order: 2,
      },
      {
        id: "opjppm",
        userId: "harrypotter",
        title: "看劇",
        color: "#FF8E9C",
        type: "todo",
        time1: new Date(2024, 2, 1, 22, 0),
        time2: new Date(2024, 1, 1, 21, 30),
        dateString: "3/1/2024",
        isDone: false,
        order: 3,
      },
      {
        id: "aasdfqesd",
        userId: "harrypotter",
        title: "看電影",
        color: "#FE6E6E",
        type: "todo",
        time1: new Date(2024, 2, 1, 22, 0),
        time2: new Date(2024, 1, 1, 18, 0),
        dateString: "3/1/2024",
        isDone: false,
        order: 4,
      },
    ],
    "3/2/2024": [
      {
        id: "aasdfqeadsfqsd",
        userId: "harrypotter",
        title: "event 3",
        color: "#C3C3C3",
        type: "event",
        time1: new Date(2024, 2, 1, 22, 0),
        time2: new Date(2024, 2, 4, 22, 0),
        dateString: "3/2/2024",
        isDone: false,
        order: 0,
      },
    ],
    "3/3/2024": [
      {
        id: "aasdfqasdfeadsfqsd",
        userId: "harrypotter",
        title: "event 3",
        color: "#EFABD8",
        type: "event",
        time1: new Date(2024, 2, 1, 22, 0),
        time2: new Date(2024, 2, 4, 22, 0),
        dateString: "3/3/2024",
        isDone: false,
        order: 0,
      },
    ],
    "3/4/2024": [
      {
        id: "aasdxcnvdfghfqeadsfqsd",
        userId: "harrypotter",
        title: "event 3",
        color: "#C47FE4",
        type: "event",
        time1: new Date(2024, 2, 1, 22, 0),
        time2: new Date(2024, 2, 4, 22, 0),
        dateString: "3/4/2024",
        isDone: false,
        order: 0,
      },
      {
        id: "aasdfqesdasdfdas",
        userId: "harrypotter",
        title: "one",
        color: "#9C7FF0",
        type: "todo",
        time1: new Date(2024, 2, 4, 22, 0),
        time2: new Date(2024, 1, 1, 18, 0),
        dateString: "3/4/2024",
        isDone: false,
        order: 1,
      },
      {
        id: "aasdfqesaaaadasdfdas",
        userId: "harrypotter",
        title: "ok",
        color: "#6997F0",
        type: "todo",
        time1: new Date(2024, 2, 4, 22, 0),
        time2: new Date(2024, 1, 1, 18, 0),
        dateString: "3/4/2024",
        isDone: false,
        order: 2,
      },
    ],
  };

  return {
    dummy,
  };
}
